-- 첫 번째 풀이
SELECT  case when month(DIFFERENTIATION_DATE) <= 3 then '1Q'
				 when month(DIFFERENTIATION_DATE) <= 6 then '2Q'
				 when month(DIFFERENTIATION_DATE) <= 9 then '3Q'
				 else '4Q'
			END AS QUARTER,
			COUNT(*) AS ECOLI_COUNT
FROM ecoli_data
GROUP BY QUARTER
ORDER BY QUARTER;
-- 두 번째 풀이
SELECT
	CONCAT(QUARTER(DIFFERENTIATION_DATE), 'Q') AS QUARTER,
	COUNT(1) AS ECOLI_COUNT
FROM ecoli_data
GROUP BY QUARTER
ORDER BY QUARTER;