SELECT QUARTER, COUNT(QUARTER) AS ECOLI_COUNT
FROM (SELECT
        CASE
        WHEN MONTH(DIFFERENTIATION_DATE) <= 3
        THEN '1Q'
        WHEN MONTH(DIFFERENTIATION_DATE) <= 6
        THEN '2Q'
        WHEN MONTH(DIFFERENTIATION_DATE) <= 9
        THEN '3Q'
        ELSE '4Q'
        END AS QUARTER
      FROM ECOLI_DATA) AS A
GROUP BY QUARTER
ORDER BY QUARTER ASC